---
title: "Mappeoppgave 3"
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(ggplot2)
```

## Oppgave 1

Vi starter med å hente ut tabellen fra nettsiden og lager et datasett.

```{r}
url <- read_html("https://www.motor.no/aktuelt/motors-store-vintertest-av-rekkevidde-pa-elbiler/217132") 

liste <- html_table(html_nodes(url, "table")[[1]], header = TRUE)
```

Så fjerner vi de to bilene som mangler verdier i datasettet.

```{r}
liste1 <-
  subset(liste, !STOPP == "x")
```

Vi rydder opp i datasettet før vi gjør verdiene om til numeriske verdier.

```{r}
liste1 <- liste1 %>% 
  rename(wltp = `WLTP-tall`, stopp = STOPP) %>% 
  mutate(Avvik = str_replace(Avvik, ",","."),
         Avvik = gsub("%", "",as.character(Avvik)), 
         stopp = gsub("km", "",as.character(stopp)), 
         wltp = substr(wltp,1,3))

liste1 <- liste1 %>% 
  mutate(wltp = as.numeric(as.character(wltp)), 
         stopp = as.numeric(as.character(stopp)), 
         Avvik = as.numeric(as.character(Avvik))) 

```

Vi plotter det og får denne figuren:

```{r}
ggplot(liste1, aes(wltp, stopp)) +
  geom_point(size = 1) +
  geom_abline(intercept = 0, slope = 1, size = 0.5, color = "red") +
  scale_x_continuous("wltp", limits = c(200,600)) +
  scale_y_continuous("stopp", limits = c(200,600)) +
  labs(title="EL-bilenes rekkevidde i forhold til oppgitte WLTP-tall") +
  theme_classic()
  
```